# **Basic Python**

### **1. Split this string**

In [ ]:
s="Hi there Mona!"
s.split()

['Hi', 'there', 'Mona!']

### **2. Use .format() to print the following string.**

Output should be: The diameter of Earth is 12742 kilometers.bold text

In [ ]:
planet="Earth"
diameter=12742

In [ ]:
print("The diameter of {} is {} kilometer".format(planet,diameter));

The diameter of Earth is 12742 kilometer


### **3. In this nest dictionary grab the word "hello"**


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

## **Numpy**

In [ ]:
import numpy as np

**4.1 Create an array of 10 zeros?**

**4.2 Create an array of 10 threes?**

In [ ]:
a=np.zeros(10)

In [ ]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
b=np.ones(10)*5
b

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### **5. Create an array of all the even integers from 30 to 55**

In [ ]:
s=np.arange(30,55,2)

In [ ]:
s

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

### **6. Create a 5x5 matrix with values ranging from 0 to 9**

In [ ]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### **7. Concatinate a and b**
**a = [3, 5, 7]**

**b = [2, 4, 6]**

In [ ]:
a=np.array([3,5,7])
b=np.array([2,4,6])

In [ ]:
np.concatenate((a,b))

array([3, 5, 7, 2, 4, 6])

### **7.1 . Concatinate a and b with sort**


In [ ]:
k=sorted(np.concatenate((a,b),axis=0))
k

[2, 3, 4, 5, 6, 7]

## **Pandas**

In [3]:
import pandas as pd

In [ ]:
d = {"names":["satheesh","anbu","karthi","palani"],"age":[21,21,20,20]}
df = pd.DataFrame(d)
df

names  age
0     satheesh   21
1         Anbu   21
2       karthi   20
3       palani   20

### **9. Generate the series of dates from 1st Nov, 2022 to 20st Dec, 2022**

In [ ]:
m= pd.date_range(start='1-11-2022',end='20-12-2022')
for i in m:
  print(i)

2022-01-11 00:00:00
2022-01-12 00:00:00
2022-01-13 00:00:00
2022-01-14 00:00:00
2022-01-15 00:00:00
2022-01-16 00:00:00
2022-01-17 00:00:00
2022-01-18 00:00:00
2022-01-19 00:00:00
2022-01-20 00:00:00
2022-01-21 00:00:00
2022-01-22 00:00:00
2022-01-23 00:00:00
2022-01-24 00:00:00
2022-01-25 00:00:00
2022-01-26 00:00:00
2022-01-27 00:00:00
2022-01-28 00:00:00
2022-01-29 00:00:00
2022-01-30 00:00:00
2022-01-31 00:00:00
2022-02-01 00:00:00
2022-02-02 00:00:00
2022-02-03 00:00:00
2022-02-04 00:00:00
2022-02-05 00:00:00
2022-02-06 00:00:00
2022-02-07 00:00:00
2022-02-08 00:00:00
2022-02-09 00:00:00
2022-02-10 00:00:00
2022-02-11 00:00:00
2022-02-12 00:00:00
2022-02-13 00:00:00
2022-02-14 00:00:00
2022-02-15 00:00:00
2022-02-16 00:00:00
2022-02-17 00:00:00
2022-02-18 00:00:00
2022-02-19 00:00:00
2022-02-20 00:00:00
2022-02-21 00:00:00
2022-02-22 00:00:00
2022-02-23 00:00:00
2022-02-24 00:00:00
2022-02-25 00:00:00
2022-02-26 00:00:00
2022-02-27 00:00:00
2022-02-28 00:00:00
2022-03-01 00:00:00


### **10. Create 2D list to DataFrame**

**l = [[1, 'satheesh', 21], [2, 'Anbu', 22], [3, 'karthi', 20],[4,'palani',20]]**

In [1]:
l= [[1, 'satheesh', 21], [2, 'Anbu', 21], [3, 'karthi', 20],[4,'palani',20]]


In [4]:
print(pd.DataFrame(l))

   0            1   2
0        Satheesh  21
1  2         Anbu  21
2  3       Karthi  20
3  4       Palani  20
